config/routes.rb
Rails.application.routes.draw do
  resources :player_characters
  resources :player_classes
  get "home/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
  get "/ping", to: "home#ping"
end

app/models/player_character.rb
class PlayerCharacter < ApplicationRecord
  include AbilityScores
  include CombatantBehavior

  belongs_to :player_class
  delegate :hit_die, :spellcasting_modifier, to: :player_class

  has_one :combatant, as: :combatable, touch: true
  behave_as_combatant
  delegate_ability_scores_to :combatant

  before_create :initialize_combatant, if: -> { combatant.nil? }
  before_create :setup_hit_points

  def setup_hit_points
    case level
    when 1
      self.max_hit_points = hit_points_at_level_one
    else
      self.max_hit_points = hit_points_at_level_one + roll_hit_points(for_level: level)
    end
  end

  def roll_hit_points(for_level: 1)
    return ArgumentError.new("for_level must be an Integer") unless for_level.is_a?(Integer)
    return ArgumentError.new("Hit points can only be rolled for levels greater than 1") if for_level && for_level < 1

    additional_hit_points = 0
    if for_level && for_level > 1
      additional_levels = for_level - level
      additional_levels.times do
        additional_hit_points += Dice.send(hit_die) + constitution_modifier
      end
    end

    additional_hit_points
  end

  def hit_points_at_level_one
    hit_die_value + constitution_modifier
  end

  def hit_die_value
    hit_die.to_s.delete("d").to_i
  end

  def roll_an_attack
    Dice::AttackRoll.new(damage_dice: damage_roll, damage_modifier: strength_modifier)
  end

  def damage_roll
    "1d4"
  end

  def get_attacked(attack_roll:)
    if attack_roll.total >= armor_class
      take_damage(amount: attack_roll.damage, damage_type: :bludgeoning)
      { success: true, attack_roll: attack_roll, message: "Hit!" }
    else
      { success: false, attack_roll: attack_roll, message: "Miss!" }
    end
  end

  def take_damage(amount:, damage_type:)
    raise ArgumentError, "Amount must be a positive Integer" unless amount.is_a?(Integer) && amount.positive?
    return if immune_to?(damage_type:)

    if resistant_to?(damage_type:)
      amount = amount / 2
    end

    if vulnerable_to?(damage_type:)
      amount = amount * 2
    end

    self.current_hit_points -= amount

    if current_hit_points <= 0
      self.current_hit_points = 0
    end
  end

  def initialize_combatant
    self.combatant = Combatant.new(combatable: self)
  end
end

app/controllers/player_characters_controller.rb
class PlayerCharactersController < ApplicationController
  before_action :set_player_character, only: %i[ show edit update destroy ]

  # GET /player_characters or /player_characters.json
  def index
    @player_characters = PlayerCharacter.all
  end

  # GET /player_characters/1 or /player_characters/1.json
  def show
  end

  # GET /player_characters/new
  def new
    @player_character = PlayerCharacter.new
  end

  # GET /player_characters/1/edit
  def edit
  end

  # POST /player_characters or /player_characters.json
  def create
    @player_character = PlayerCharacter.new(player_character_params)

    respond_to do |format|
      if @player_character.save
        format.html { redirect_to @player_character, notice: "Player character was successfully created." }
        format.json { render :show, status: :created, location: @player_character }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @player_character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /player_characters/1 or /player_characters/1.json
  def update
    respond_to do |format|
      if @player_character.update(player_character_params)
        format.html { redirect_to @player_character, notice: "Player character was successfully updated." }
        format.json { render :show, status: :ok, location: @player_character }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @player_character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /player_characters/1 or /player_characters/1.json
  def destroy
    @player_character.destroy!

    respond_to do |format|
      format.html { redirect_to player_characters_path, status: :see_other, notice: "Player character was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player_character
      @player_character = PlayerCharacter.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def player_character_params
      params.expect(player_character: [ :name, :level, :player_class_id ])
    end
end

app/helpers/player_characters_helper.rb
module PlayerCharactersHelper
end

app/views/player_characters/_form.html.erb
<%= form_with(model: player_character, class: "contents") do |form| %>
  <% if player_character.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(player_character.errors.count, "error") %> prohibited this player_character from being saved:</h2>

      <ul class="list-disc ml-6">
        <% player_character.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": player_character.errors[:name].none?, "border-red-400 focus:outline-red-600": player_character.errors[:name].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :level %>
    <%= form.number_field :level, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": player_character.errors[:level].none?, "border-red-400 focus:outline-red-600": player_character.errors[:level].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :player_class_id %>
    <%= form.text_field :player_class_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": player_character.errors[:player_class_id].none?, "border-red-400 focus:outline-red-600": player_character.errors[:player_class_id].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/player_characters/_player_character.html.erb
<div id="<%= dom_id player_character %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Name:</strong>
    <%= player_character.name %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Level:</strong>
    <%= player_character.level %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Player class:</strong>
    <%= player_character.player_class_id %>
  </div>
</div>

app/views/player_characters/edit.html.erb
<% content_for :title, "Editing player character" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing player character</h1>

  <%= render "form", player_character: @player_character %>

  <%= link_to "Show this player character", @player_character, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to player characters", player_characters_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/player_characters/index.html.erb
<% content_for :title, "Player characters" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Player characters</h1>
    <%= link_to "New player character", new_player_character_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="player_characters" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @player_characters.any? %>
      <% @player_characters.each do |player_character| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render player_character %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", player_character, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_player_character_path(player_character), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", player_character, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No player characters found.</p>
    <% end %>
  </div>
</div>

app/views/player_characters/new.html.erb
<% content_for :title, "New player character" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New player character</h1>

  <%= render "form", player_character: @player_character %>

  <%= link_to "Back to player characters", player_characters_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/player_characters/show.html.erb
<% content_for :title, "Showing player character" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing player character</h1>

  <%= render @player_character %>

  <%= link_to "Edit this player character", edit_player_character_path(@player_character), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to player characters", player_characters_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this player character", @player_character, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>